### ISSUE TITLE
API の概要をドキュメンテーションサイトのコンテンツの仕上げ

### ISSUE THREAD

**Issue by ShinichiNishikawa** [takamatsu-city/docs.takamatsu-fact.com#4]
コンテンツは
https://github.com/takamatsu-city/docs.takamatsu-fact.com/blob/main/README.md
にあるので、この穴埋めを行う。

**Comment by ShinichiNishikawa** [comment]
@keichan34  こちらのドキュメンテーション、見出しまではできています。コンテンツ、書き換えられますか？

**Comment by keichan34** [comment]
@ShinichiNishikawa 具体的には

https://github.com/takamatsu-city/docs.takamatsu-fact.com/blob/main/README.md#sdk-%E3%81%AE%E8%A9%B3%E7%B4%B0
https://github.com/takamatsu-city/docs.takamatsu-fact.com/blob/main/README.md#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA

この二つのセクションを埋める、という理解であってますか？

**Comment by ShinichiNishikawa** [comment]
@keichan34 2点確認お願いします。

# 1. 埋める範囲
上記の2つに加えて、座標や空間IDから情報を取得できるところもお願いしたいです。

https://github.com/takamatsu-city/docs.takamatsu-fact.com/blob/main/README.md#%E9%83%BD%E5%B8%82%E6%83%85%E5%A0%B1api%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B

# 2. SDK そのもの

以下の記述でデータを表示する機能は残るという理解であっていますか？

```
const myCity = new city.Takamatsu.Map();

myCity.on('load', () => {  
  
  myCity.loadData("商業地域")
  
  myCity.loadData('第一種低層住居専用地域', {
    'fill-color': 'purple',
  })
    
})
```
